# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [2]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", np.add(mat1,mat2))
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", (3*mat1 - 2*mat2))


print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[9 5 2]
 [1 8 1]
 [5 6 6]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[4 5 5]
 [8 6 4]
 [6 5 5]]

Addition
------------------
 [[13 10  7]
 [ 9 14  5]
 [11 11 11]]

Multiplication
------------------
 [[36 25 10]
 [ 8 48  4]
 [30 30 30]]

Division
------------------
 [[2.25       1.         0.4       ]
 [0.125      1.33333333 0.25      ]
 [0.83333333 1.2        1.2       ]]

Linear combination: 3*A - 2*B
-----------------------------
 [[ 19   5  -4]
 [-13  12  -5]
 [  3   8   8]]

Addition of a scalar (100)
-------------------------
 [[109 105 102]
 [101 108 101]
 [105 106 106]]

Exponentiation, matrix cubed here
----------------------------------------
 [[729 125   8]
 [  1 512   1]
 [125 216 216]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[3.         2.23606798 1.41421356]
 [1.         2.82842712 1.       

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [3]:
from numpy.random import randint as ri

In [4]:
from numpy.random import randint as ri
mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[4 3 4]
 [6 9 6]
 [7 1 6]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[8 6 3]
 [3 2 7]
 [5 6 6]]


In [5]:
np.mean(mat1)

5.111111111111111

In [6]:
np.median(mat1)

6.0

In [7]:
from numpy.random import randint as ri
mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",np.sum(mat1, axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",np.prod(mat1,axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",np.prod(mat1,axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",np.mean(mat1))


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",np.std(mat1))


mat1 = ri(1,99,9).reshape(3,3)
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.std(mat1))


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",np.var(mat1))


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))


1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[7 6 8]
 [3 9 2]
 [8 7 2]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[3 4 6]
 [9 6 7]
 [3 5 7]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 52

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [18 22 12]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [21 14 17]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [336  54 112]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [168 378  32]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 5.777777777777778

Standard deviation of all numbers in 1st matrix
 -------------------------------------------------- 
 2

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [8]:
##Solution

mat = np.random.randint(1,100,9).reshape(3,3)
print("\n 3*3 matrix\n",'-'*10,"\n",mat)


mat_modified = mat.reshape(9,1)
print("\n 9*1 matrix\n",'-'*10,"\n",mat_modified)


 3*3 matrix
 ---------- 
 [[12 51 44]
 [47 13 10]
 [ 9 28 61]]

 9*1 matrix
 ---------- 
 [[12]
 [51]
 [44]
 [47]
 [13]
 [10]
 [ 9]
 [28]
 [61]]


### 4.Sort

In [9]:
A = np.random.randint(1,100,10) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [98  1 78 23 80 62 87 19 23 50]

Here is the sorted vector
 -------------------------------------------------- 
 [ 1 19 23 23 50 62 78 80 87 98]


In [10]:
M = np.random.randint(1,100,25).reshape(5,5) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis = 1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M,axis = 0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[ 6 84 58 90  7]
 [69 15 91 13 18]
 [94 11 77 99 37]
 [29 73 40 69 92]
 [74 80 64 71 43]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[ 6  7 58 84 90]
 [13 15 18 69 91]
 [11 37 77 94 99]
 [29 40 69 73 92]
 [43 64 71 74 80]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 6 11 40 13  7]
 [29 15 58 69 18]
 [69 73 64 71 37]
 [74 80 77 90 43]
 [94 84 91 99 92]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [11]:
# Fill the following ***** with appropriate solution.
a= np.random.randint(1,100,10)
b= np.random.randint(1,100,10)
c= np.random.randint(1,100,10)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:",np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Min of a:", np.min(a))
print("Min of b:", np.min(b))


print("Min of a location:", np.argmin(a))
print("Min of b location:", np.argmin(b))
print("Min of c location:", np.argmin(c))

a: [99 17  1  9 14 52 91  4 80  7]
b: [71  7 63 31 25  9  4 48 51 18]
c: [76 23 29 62 52 93 80  2 63 86]
Max of a: 99
Max of b: 71
Max of a location: 0
Max of b location: 0
Max of c location: 5
Min of a: 1
Min of b: 4
Min of a location: 2
Min of b location: 6
Min of c location: 7


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [12]:
mat1 = np.random.randint(1,100,9).reshape(3,3)
mat2 = np.random.randint(1,100,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat1,mat2))


1st Matrix of random single-digit numbers
----------------------------------------
 [[68 34 70]
 [27 54 89]
 [10 35 33]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[58 55 67]
 [24 46 47]
 [72 58 49]]

Sq-root of 1st matrix using np
------------------
 [[8.24621125 5.83095189 8.36660027]
 [5.19615242 7.34846923 9.43398113]
 [3.16227766 5.91607978 5.74456265]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[3.40427605e+29 5.83461743e+14 2.51543867e+30]
 [5.32048241e+11 2.83075330e+23 4.48961282e+38]
 [2.20264658e+04 1.58601345e+15 2.14643580e+14]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[1.83250891 1.53147892 1.84509804]
 [1.43136376 1.73239376 1.94939001]
 [1.         1.54406804 1.51851394]]

Modulo reminder using np
 -------------------------------------------------- 
 [[10 34  3]
 [ 3  8 42]
 [10 35 33]]


### 7.Generating matrices from distributions

In [13]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [14]:
np.random.normal(0, 1, 10)

array([ 1.31579727,  0.47881954, -0.78915489, -0.52460344, -0.14959842,
       -2.36494589,  1.29068298,  1.72996923, -0.90568205,  0.15467167])

In [15]:
np.random.uniform(0, 1, 6).reshape(2,3)

array([[0.62290463, 0.33372938, 0.70735477],
       [0.86271268, 0.59280088, 0.07107828]])

In [16]:
print("\nRandom number generation (from Uniform distribution\n")
print(np.random.uniform(0, 1, 6).reshape(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("\nNumbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal\n")
print(np.random.normal(0, 1, 10))

print("\nRandom integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix\n")
print(np.random.randint(1,100,10).reshape(2,5)) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.multinomial(20, [1/6.]*6)) # 20 samples drawn from a dice throw


Random number generation (from Uniform distribution

[[0.69577831 0.88973996 0.72276634]
 [0.29806924 0.61296477 0.78722876]]

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal

[ 0.20176017  0.44694192 -0.41709443  1.60655575  0.73857852 -2.51357283
  1.45692327 -1.02049042 -0.50917349 -0.22703286]

Random integer vector: [96 64 41 21  4 68 48 96 61 66]

Random integer matrix

[[63 12 67 87 23]
 [77 26 76 19 42]]

20 samples drawn from a dice throw: [3 3 3 2 5 4]


### 8.Find the nearest value from a given number in an array using NumPy.

In [17]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

arr = np.random.randint(1,12,5)
print("\nArray is:", arr)

val = 10
print("\nValue is:", val)

def find_nearest(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    print("\nIndex where difference is minimum:", idx)
    print("\nElement:", array[idx])

find_nearest(arr, val)


Array is: [11  6  1  1  7]

Value is: 10

Index where difference is minimum: 0

Element: 11


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [18]:
# Provide the dimensions of matrix in form of list
dimensions = [3,3]
rowNum=dimensions[0]
colNum=dimensions[1]
multilist = [[0 for col in range(colNum)] for row in range(rowNum)]

for row in range(rowNum):
    for col in range(colNum):
        multilist[row][col]= row*col
        
print(multilist)

[[0, 0, 0], [0, 1, 2], [0, 2, 4]]
